version: 1.6.1.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_informational_version: '$(APPVEYOR_BUILD_VERSION).$(APPVEYOR_BUILD_NUMBER) $(APPVEYOR_REPO_COMMIT)'
  
before_build:
- cmd: nuget restore

build:
  project: XPTable.sln
  verbosity: minimal
  
configuration:
  - Release  

after_build:
- nuget pack XPTable.csproj

test:
  assemblies:
    - UnitTest\bin\Test\UnitTest.dll
    
artifacts:
- path: bin
- path: XPTable*.nupkg